### PR TITLE
fix Caddy directory

### PR DESCRIPTION
**Pull request by NauxLiu**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you give a description of the error you are encountering and trying to fix?

**Comment by NauxLiu** [comment]
After upgrading from older version, the directory ~/.valet/Caddy not yet exist, execute 'valet secure' will meet error:

```
PHP Warning:  file_put_contents(/Users/xuan/.valet/Caddy/test.dev): failed to open stream: No such file or directory in /Users/xuan/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 125

Warning: file_put_contents(/Users/xuan/.valet/Caddy/test.dev): failed to open stream: No such file or directory in /Users/xuan/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 125
PHP Warning:  chown(): No such file or directory in /Users/xuan/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 254

Warning: chown(): No such file or directory in /Users/xuan/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 254
```

**Comment by J5Dev** [comment]
Im getting a similar error, which this looks like itis not restricted to just securing, as I get the error when changing the domain valet is using....

`SitesValet  valet domain valet
PHP Warning:  file_put_contents(/Users/Chris/.valet/Caddy/): failed to open stream: Is a directory in /Users/Chris/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 125
PHP Stack trace:
PHP   1. {main}() /Users/Chris/.composer/vendor/laravel/valet/cli/valet.php:0
PHP   2. Symfony\Component\Console\Application->run() /Users/Chris/.composer/vendor/laravel/valet/cli/valet.php:267
PHP   3. Symfony\Component\Console\Application->doRun() /Users/Chris/.composer/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Component\Console\Application->doRunCommand() /Users/Chris/.composer/vendor/symfony/console/Application.php:186
PHP   5. Symfony\Component\Console\Command\Command->run() /Users/Chris/.composer/vendor/symfony/console/Application.php:791
PHP   6. call_user_func:{/Users/Chris/.composer/vendor/symfony/console/Command/Command.php:254}() /Users/Chris/.composer/vendor/symfony/console/Command/Command.php:254
PHP   7. Silly\Application->Silly\{closure}() /Users/Chris/.composer/vendor/symfony/console/Command/Command.php:254
PHP   8. Invoker\Invoker->call() /Users/Chris/.composer/vendor/mnapoli/silly/src/Application.php:78
PHP   9. call_user_func_array:{/Users/Chris/.composer/vendor/php-di/invoker/src/Invoker.php:82}() /Users/Chris/.composer/vendor/php-di/invoker/src/Invoker.php:82
PHP  10. Silly\Application->{closure:/Users/Chris/.composer/vendor/laravel/valet/cli/valet.php:55-71}() /Users/Chris/.composer/vendor/php-di/invoker/src/Invoker.php:82
PHP  11. Facade::resecureForNewDomain() /Users/Chris/.composer/vendor/laravel/valet/cli/valet.php:66
PHP  12. Facade::__callStatic() /Users/Chris/.composer/vendor/laravel/valet/cli/valet.php:66
PHP  13. Valet\Site->resecureForNewDomain() /Users/Chris/.composer/vendor/laravel/valet/cli/includes/facades.php:24
PHP  14. Valet\Site->secure() /Users/Chris/.composer/vendor/laravel/valet/cli/Valet/Site.php:103
PHP  15. Valet\Filesystem->putAsUser() /Users/Chris/.composer/vendor/laravel/valet/cli/Valet/Site.php:135
PHP  16. Valet\Filesystem->put() /Users/Chris/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php:141
PHP  17. file_put_contents() /Users/Chris/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php:125`

Im guessing this check needs to done in a few more places.

**Comment by adamwathan** [comment]
As per the upgrade instructions, you should run `valet install` when upgrading from < 1.1.0:

https://laravel.com/docs/5.2/valet#release-notes

This should create any of the necessary files and directories.

**Pull request closed without merging**
