### PR TITLE
Alias dev-master to 2.x-dev

### PR DESCRIPTION
**Pull request by simensen**
You all seem to be pretty good about updating cutting new releases and updating version numbers quickly, but I thought it would be nice to allow people to target `@dev` more easily (like `^2.10@dev` or something).

### CODE REVIEW

**Comment by drbyte** [comment]
Ya, that's fair. And it helps target a version-specific `@dev` series too, instead of generic `@dev-master`.

**Comment by drbyte** [comment]
@simensen Double-checking: merging this doesn't require tagging a new release for this alias to have immediate effect, does it?

**Comment by simensen** [comment]
I am pretty sure as soon as it hits master and packaging picks it up it will be active regardless of any tagging. :)

**Comment by mattstauffer** [comment]
Thanks Beau!!

**Pull request merged**
