### PR TITLE
Fix magento2 driver

### PR DESCRIPTION
**Pull request by mischabraam**
Fix magento2 driver + simplify, let mode determine by Magento env config

Fixes https://github.com/laravel/valet/discussions/1119 and https://github.com/laravel/valet/issues/592

### CODE REVIEW

**Comment by mattstauffer** [comment]
@mischabraam Thanks so much for this PR!

Because I have no experience with Magento, this is hard for me to review. Do you have any other members of the Magento community who could review this for us?

**Comment by mischabraam** [comment]
Sure, no problem.

**Comment by mattstauffer** [comment]
@mischabraam I'm OK to merge this if you can manage the conflicts in this PR. Thank you!

**Comment by driesvints** [comment]
Thanks all.

**Pull request merged**
