### PR TITLE
Remove '/Users/' prefix

### PR DESCRIPTION
**Pull request by pespantelis**
If someone uses different home directory (like me) it does not work.

### CODE REVIEW

**Comment by nilportugues** [comment]
@pespantelis removing will do? Not sure... 

Maybe using system's `$HOME` variable makes more sense.

**Comment by pespantelis** [comment]
@nilportugues as you can see, I have used the appropriate variables, so that the `/Users/` prefix gonna be removed.

@sagalbot if you had already installed it, you should remove this file:
```
/usr/local/etc/dnsmasq.conf
```
Then, run the `valet install` again.
Of course, you need to wait for the merge of this pull request (or another), or you can change it manually until it will be happening.

**Comment by vegamx** [comment]
I would like to see this PR merged. I was pulling out my hair wondering why everyone talks wonders about Valet and it wasn't working smoothly for me. Now i see the cause, i have 2nd drive with my whole home folder there.

**Comment by adamwathan** [comment]
@sagalbot sort of a crappy answer until we have a chance to put together some common troubleshooting info, but follow this Twitter thread, I helped someone else earlier today and basically everything worth trying and investigating is mentioned here: https://twitter.com/UziUx/status/730043841227591681

**Comment by adamwathan** [comment]
Most common things to try:

- Delete `~/.valet` and re-run `valet install`
- Log out of your OSX user account and back in, sometimes this is needed for the DNS resolver changes to get picked up
- Look for errors in PHP FPM logs: `cat /usr/local/opt/php70/var/log/php-fpm.log`
- Verify `dnsmasq` and `php70` are running as root in `brew services list`
- Make sure `/usr/local/var/log` exists so PHP FPM can write logs there
- Verify PHP FPM is running by running `ps aux | grep php` and looking for a couple of FPM instances
- Verify `User` and `Group` are set to your user name and the `staff` group in `/usr/local/etc/php/7.0/php-fpm.d/www.conf`, the installer should do this for you but worth double checking

**Comment by adamwathan** [comment]
Can you `cat /etc/resolver/dev` ?

**Comment by adamwathan** [comment]
Try `scutil --dns` and check it has an entry that looks something like:

```
resolver #8
  domain   : dev
  nameserver[0] : 127.0.0.1
  flags    : Request A records, Request AAAA records
Reachable, Local Address, Directly Reachable Address
```

**Comment by adamwathan** [comment]
Also `dns-sd -G v4 foobar.dev` and see if the DNS appears to be resolving to `127.0.0.1`

**Comment by adamwathan** [comment]
Do you mind sharing the entire output of `scutil --dns` ?

**Comment by adamwathan** [comment]
Ugh not sure what else to check honestly :( Gonna keep thinking on it!

**Comment by adamwathan** [comment]
`ps aux | grep caddy` show Caddy running?

**Comment by adamwathan** [comment]
Ah Caddy is not running!

**Comment by adamwathan** [comment]
Try...

`sudo ~/.composer/vendor/bin/caddy --conf=/Users/sagalbot/.valet/Caddyfile`

...and see if there's any error output.

**Comment by adamwathan** [comment]
`ls -la ~/.composer/vendor/laravel/valet/bin` ?

**Comment by adamwathan** [comment]
Try:

```
rm -rf ~/.composer/vendor
rm ~/.composer/composer.lock
composer global update
```

...just to be sure have fresh files, maybe Composer didn't make the symlink to `~/.composer/vendor/bin`

**Comment by adamwathan** [comment]
Try this as well:

`sudo ~/.composer/vendor/laravel/valet/bin/caddy --conf=/Users/sagalbot/.valet/Caddyfile`

...then see if your sites work

**Comment by vegamx** [comment]
I am following up this thread because i have the same problem as sagalbot.

I got this after running the last suggestion:

`sudo ~/.composer/vendor/laravel/valet/bin/caddy --conf=/Volumes/500GBHD/ricardo/.valet/Caddyfile
2016/05/11 13:03:19 Caddyfile:1 - Parse error: No files matching import pattern /Users/ricardo/.valet/Caddy/*`

**Comment by adamwathan** [comment]
Try deleting the first line (the import directive) from `~/.valet/Caddyfile` and running:

`sudo ~/.composer/vendor/laravel/valet/bin/caddy --conf=/Volumes/Documents/sagalbot/.valet/Caddyfile`

...again

**Comment by vegamx** [comment]
`Activating privacy features... done.
:80
Warning: File descriptor limit 2560 is too low for production sites. At least 4096 is recommended. Set with "ulimit -n 4096".`

**Comment by adamwathan** [comment]
@vegamx That error is no big deal in my experience, should still run.

**Comment by adamwathan** [comment]
@sagalbot It shouldn't complete, that's the server running :) Leave it running and try hitting a site.

**Comment by adamwathan** [comment]
@sagalbot Can I DM you somewhere? If you're free for 10 min I'd love to screenshare and help sort this one out.

**Comment by adamwathan** [comment]
Screenhero?

**Comment by vegamx** [comment]
Please share the answer if you find the solution :) Thanks for the troubleshooting, Adam.

**Comment by adamwathan** [comment]
@vegamx definitely will!

**Comment by adamwathan** [comment]
@sagalbot Add me adam dot wathan at gmail on Screenhero 👍

**Comment by adamwathan** [comment]
@vegamx The problem @sagalbot was having was related to running Plex, which was using port 53 for it's DNS stuff, causing dnsmasq not to start properly. Stopping Plex allowed Valet to start properly.

Try running `sudo lsof -i :53` to find out if anything is already running on port 53 on your machine to see if it's a similar issue.

**Comment by adamwathan** [comment]
Here were our steps to resolving:

1. Run `sudo brew services stop dnsmasq` to kill the background dnsmasq process
2. Manually start dnsmasq in the foreground using `sudo /usr/local/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /usr/local/etc/dnsmasq.conf` and look for errors
3. We saw that dnsmasq was complaining that `dnsmasq: failed to create listening socket for 192.168.10.1: Permission denied`
4. We know dnsmasq runs on port 53, so check for other services on port 53 with `sudo lsof -i :53`
5. Saw Python was running on the port, turns out it was a Plex related thing.
6. Killed the Python process, ran `valet install` again.
7. Everything is working gloriously.

**Comment by vegamx** [comment]
Finally fixed it with your help guys :)

Here's what worked:

1. Deleted the `~/.valet folder`
2. `composer global update laravel/valet`
3. Follow steps pointed out by @pespantelis about deleting `/usr/local/etc/dnsmasq.conf`
4. `valet install`
5. `cd ~/Sites`
7. `valet park`
6. `laravel new zonda`
7. `ping zonda.dev`
8. #ThatsFukinZonda :D 

Thank you all for your time troubleshooting this.

**Comment by victorhguillen** [comment]
I have an issue with caddy, the only way to run the server is manual:
sudo ~/.composer/vendor/laravel/valet/bin/caddy --conf=/Users/myuser/.valet/Caddyfile

Inside the laravel project ~/Sites/blog/

Otherwise caddy don't run at login.

**Pull request merged**
