### PR TITLE
Add status command

### PR DESCRIPTION
**Pull request by mattstauffer**
Add a `status` command that checks to make sure Valet and its services are installed, running, and configured correctly.

### CODE REVIEW

**Comment by mattstauffer** [comment]
@nicoverbruggen I haven't checked in with you lately.. would this status tool help you at all? I don't know if you're actively checking the status of the Brew services or anything else already?

**Comment by nicoverbruggen** [comment]
@mattstauffer I actively check the Homebrew services, yes. 

The annoying part is that Valet's services run as admin, and some users will incorrectly run their services using their own user account (especially if they themselves installed PHP using `brew install php`): in that case, services might not be running correctly. 

So I tend to run both of these:

```
sudo brew services info --all --json
brew services info --all --json
```

and depending on what info I need I'll pick out the information from here.

This can also be used to find out if a user has a PHP service running incorrectly. (i.e. phpmon will shut down all PHP services running as the user account (as output of `brew services info --all --json`) and start the correct ones as root by running `sudo brew services start php@x.x`).

The services manager in PHP Monitor can be found [here](https://github.com/nicoverbruggen/phpmon/blob/e29ca9e1ad17b6bba9ef693df5f12ef38fc9f749/phpmon/Domain/App/ServicesManager.swift#L19).

**Comment by mattstauffer** [comment]
@nicoverbruggen Thanks! Would this native Valet status command have any value to you, or are you happy with what you're currently doing?

**Comment by nicoverbruggen** [comment]
@mattstauffer I'll stick with what I'm doing for now, yes!

**Comment by mattstauffer** [comment]
Nico, the idea to check both the root and the user versions of the services was exactly what I needed to make this command more correct. Thank you!!

**Pull request merged**
