### PR TITLE
Drupal 7 & 8 Driver

### PR DESCRIPTION
**Pull request by Cybnext**
This driver adds support for Drupal 7 and 8.

### CODE REVIEW

**Comment by taylorotwell** [comment]
How does this handle the situations when Drupal does things like /update.php/more/path/here?

**Comment by Cybnext** [comment]
@taylorotwell 	I've just rewritten the front controller code to handle this. Also while doing so, I found that this method also covered for some of the previous checks and those have since been removed.

**Comment by Cybnext** [comment]
@taylorotwell is there something I can do to help move this along?

**Comment by barryvdh** [comment]
Perhaps fix the merge conflicts? ;)

**Comment by jaymiejones86** [comment]
@Cybnext anything I can do to help get this PR back to green so it can hopefully get merged soon?

**Comment by Cybnext** [comment]
Alright, back to green, hopefully we can get this merged now :)

**Comment by dustinleblanc** [comment]
@Cybnext I was just about to do a version of this that's compatible with drupal-composer/drupal-project (docroot is nested at `/web/`). Would it make sense to just add the path logic into the checks here? All the conditionals are getting silly, but this structure is gaining popularity in the Drupal-verse.

**Comment by cferthorney** [comment]
Given Drupal has launched alpha support for it's [own packagist/composer](https://www.drupal.org/node/2718229) I'd suggest composer support is a must.  It may as well default to `web/` as the regex can always be updated by another PR if necessary.  I can't be sure if drupal.org will suggest an alternative location for things (IE over `web/`) or not though.

**Comment by thijsvdanker** [comment]
> Given Drupal has launched alpha support for it's own packagist/composer I'd suggest composer support is a must.

I think this should just get merged and a new PR for the (alpha) composer support would be more appropriate.

**Comment by jaymiejones86** [comment]
I would have to agree. Iterate on the basic implementation.
On Tue, 28 Jun 2016 at 6:15 PM, Thijs van den Anker <
notifications@github.com> wrote:

> Given Drupal has launched alpha support for it's own packagist/composer
> I'd suggest composer support is a must.
>
> I think this should just get merged and a new PR for the (alpha) composer
> support would be more appropriate.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/laravel/valet/pull/48#issuecomment-228982306>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABU36ViIfeCq_YDSDCpl3gFcziV8zYuhks5qQNgJgaJpZM4Iaj-z>
> .
>
-- 
Jaymie Jones
@pixelstackcom
http://jaymiejonesphoto.com
http://codercatchup.com
https://devbase.io

**Comment by Cybnext** [comment]
I would agree with getting the basic pulled into master. Hopefully that can happen soon, kind of frustrating to have this sitting green for another month

**Comment by McGo** [comment]
Any progress on this? Is there anything that has to be done before merging into master?

**Comment by Cybnext** [comment]
@McGo Nope, nothing we can do at this point. It's been ready for awhile now and could easily be merged into master, just have to wait for a maintainer to do it, I guess.

**Comment by taylorotwell** [comment]
There ya go.

**Pull request merged**
