### PR TITLE
Add support for Drupal

### PR DESCRIPTION
**Pull request by Cybnext**

### CODE REVIEW

**Comment by taylorotwell** [comment]
http://d.pr/i/pTxP/1Yr1Qd2n

Please test these drivers! :)

**Comment by taylorotwell** [comment]
Drupal 8 doesn't seem to have a misc/drupal.js

**Comment by Cybnext** [comment]
I'll look into a way to make sure Drupal 6, 7 and 8 are supported. Forgot Drupal 8 did a major rewrite/restructure

**Comment by taylorotwell** [comment]
Closing this totally. Even after I got it going installer fails because front controller detection isn't right and Drupal does all kinds of weird mess it appears. Please test that it is FULLY working if you submit again.

**Pull request closed without merging**
