### PR TITLE
PHP 7.4 support

### PR DESCRIPTION
**Pull request by ravenberg**
I added `php@7.4` in the `SUPPORTED_PHP_VERSIONS` and `LATEST_PHP_VERSION` constants to allow for php 7.4 support, as discussed in issue https://github.com/laravel/valet/issues/846. So we can all enjoy the new version with Valet. 🎉

### CODE REVIEW

**Comment by sagar-noovosoft** [comment]
Good work!

**Comment by mingyoung** [comment]
👍

**Comment by vicgonvt** [comment]
Thanks!

**Comment by freekmurze** [comment]
I can confirm that this change works 👍

**Pull request merged**
