### PR TITLE
Secure custom domains

### PR DESCRIPTION
**Pull request by mgussekloo**
I have attempted a new pull request, one that includes a test and takes the feedback from [#1294](https://github.com/laravel/valet/pull/1294) into account. Apologies if this is simply an unwanted feature.

Update the domain() function to include the default TLD only if the $domain variable does not include a dot. This lets you secure custom domains, e.g. "valet secure [www.mywebsite.com](http://www.mywebsite.com/)". (You would also have to add [www.mywebsite.com](http://www.mywebsite.com/) to your hosts file and create a symlink or folder in the Valet site directory, of course.)

### CODE REVIEW

**Comment by mattstauffer** [comment]
I don't see any value in Valet securing domains that Valet doesn't serve. Valet is structured around serving everything under one TLD and I think we should keep the API constrained to that.

Thank you for the PR, though!

**Comment by zkingdesign** [comment]
This would be really nice to have. @mgussekloo do you have a tutorial where you show how this can be used?

**Comment by mgussekloo** [comment]
@zkingdesign Sure, it's nothing too special. 

- Make sure Valet site is reachable through the custom domain name (see [this tutorial from Stefan Bauer](https://stefanbauer.me/articles/how-to-use-custom-domains-with-different-tlds-on-laravel-valet))
- in the folder where i "park" my valet sites, i create a folder with the domain name e.g., the folder "www.myexample.com"
- add the domain to my /etc/hosts so www.myexample.com resolves to 127.0.0.1

Then, simply ask Valet to secure the custom domain, e.g. "valet secure www.myexample.com"
Make sure you modify Valet (see my pull request), else it will stubbornly secure "www.myexample.com.test" instead.

**Comment by zkingdesign** [comment]
Thanks @mgussekloo for your help!

**Pull request closed without merging**
