### PR TITLE
Adding --without-apache option to php package

### PR DESCRIPTION
**Pull request by dbpolito**

### CODE REVIEW

**Comment by adamwathan** [comment]
Hey @dbpolito, thanks! Can you give some more details behind the benefits of this? Does it speed up installation significantly, etc.? Does it trigger a compilation vs. being able to use a prebuilt version from Homebrew?

**Comment by dbpolito** [comment]
Yes, it speed ups the installation a bit, and also doesn't install apache modules, which we don't use at all... as we use Caddy.

**Comment by drbyte** [comment]
In my experience if I add compile-time options to php (with homebrew), then it makes installing other homebrew php modules fail. (ie: php-intl, php-mcrypt, etc). I'd prefer not to have that headache. 

YMMV; just something to consider when testing if this idea is merged.

**Comment by adamwathan** [comment]
Going to hold off on this for now and just roll with the default installation, but might reconsider down the road.

**Pull request closed without merging**
