### PR TITLE
Extending the WordPress driver to run sites in subdirectories

### PR DESCRIPTION
**Pull request by zetrider**
The WordPress site can be installed in a subdirectory of the root folder. The current driver change allows you to deploy sites in subdirectories.

### CODE REVIEW

**Comment by mattstauffer** [comment]
I'm not a WordPress dev, so I've asked for help:

https://twitter.com/stauffermatt/status/1598343856126394368

**Comment by rosswintle** [comment]
Hi folks, I'm just looking into helping Matt review and test this. Great to see the WordPress driver being improved.

Installing WordPress in a subdirectory can mean one of a few different things.

Could you please give an example of what this PR lets you do, specifically stating both the directory/path and the root URL of the site so that we can review and test what you are expecting to work?

Thanks

**Comment by ihorvorotnov** [comment]
@rosswintle FYI running WordPress core from a subdir (installed as a package via Composer - e.g. Roots and similar setups) works just fine out of the box, using this for years.

**Comment by seemly** [comment]
I don't know why, but this PR didn't work for me.

I did manage to find a repo that does work for subdirectory-based WordPress multisite functionality. Well, with the exception of the missing return types:

https://github.com/Objectivco/WordPressMultisiteSubdirectoryValetDriver/blob/master/WordPressMultisiteSubdirectoryValetDriver.php

**Comment by mattstauffer** [comment]
As a non-WP dev, I can't act on this myself; I'm not seeing consensus above, or any continued conversation, so I'm going to close it.

**Pull request closed without merging**
