### PR TITLE
Ensure domain is read from the configuration file for dnsmasq

### PR DESCRIPTION
**Pull request by michaeldyrynda**
Whilst you can configure the domain via `config.json`, the domain is not read from the configuration file when writing to `dnsmasq.conf`

### CODE REVIEW

**Comment by taylorotwell** [comment]
So I'm guessing you update domain in config and then run `valet install` again?

**Comment by michaeldyrynda** [comment]
That's currently the only way to go about it. I didn't want to introduce any extra CLI arguments. I could modify this to do something like `valet install <domain=dev>` if you'd like?

**Comment by michaeldyrynda** [comment]
image

Is this sufficiently zonda? 😀

**Comment by adamwathan** [comment]
I think we're going to want to do something to mark any `/etc/resolver/*` files we create so we can clean them up if someone wants to use a different TLD. Right now if you do a normal `valet install` and then a `valet install local` afterwards, it leaves `/etc/resolver/dev` behind, and we probably want to delete that if we know we're the ones who created it. Pow does this [with a comment](https://github.com/basecamp/pow/blob/master/src/templates/installer/resolver.eco#L1) so that it's easy for them to know if they can safely delete that file.

It looks like this PR is not creating a new `/etc/resolver/{tld}` yet for the user specified TLD either, so will need to do that.

Ultimately I wonder if we want to also add a `valet tld {tld}` command that just swaps this stuff, seems overkill to rewrite all the launch daemons and everything unnecessarily. I do like being able to specify it on install as well though.

**Comment by michaeldyrynda** [comment]
Yeah, still a WIP as I discovered some issues (like `dnsmasq.conf` being overwritten, but `config.json` isn't). I just tweaked that so that the domain is merged from the command.

Another issue i've found is that dnsmasq gets a little sticky if you change the TLDs around. Restarting dnsmasq and flushing cache doesn't do the trick; have needed to restart for a changed TLD to stick. There *must* be some command to get it to work, but I'm yet to find it. Will work some more on this tomorrow; it's late.

**Comment by adamwathan** [comment]
Late? It's only 10:09 AM man 😉

**Comment by taylorotwell** [comment]
Did this a little different. Fixed a few bugs and made sure that it also applies when using Valet share.

**Comment by michaeldyrynda** [comment]
Thanks Taylor :)

**Pull request closed without merging**
