### PR TITLE
Fix extra parameters for share tool, fixes #1494

### LINKED ISSUE #1494: Passing arguments to Ngrok broken in v.4.8.0
### Description

v4.8.0 breaks passing arguments like `--domain` with the `valet share` command. Only tested with Ngrok.
For now I've downgraded back to v4.7.1, since it works in this version

### Steps To Reproduce

```bash
$ valet share-tool ngrok
$ valet share --domain=custom.domain
```

### Diagnosis

N/A

### PR DESCRIPTION
**Pull request by rcknr**
There was a typo in my previous PR that led to a problem passing extra arguments to share tools. Fixes #1494

### CODE REVIEW

**Comment by drbyte** [comment]
Yes, that seems to be the right fix.
/cc @mattstauffer

**Comment by drbyte** [comment]
@rcknr Can you edit your post above, and change `See #1494` to `Fixes #1494`. That way Github will automatically close the related issue when this PR is merged (it uses the words "fixed" or "fix" or "fixes", or "closes", in the original PR post, to automatically trigger that).

**Comment by kiritokatklian** [comment]
Any updates on when we can expect this to be merged? 😄

**Comment by mattstauffer** [comment]
Thanks for the PR @rcknr!

**Pull request merged**
