### PR TITLE
Fixes Valet\Drivers\LocalValetDriver not found error

### PR DESCRIPTION
**Pull request by fylzero**
This seems to resolve https://github.com/laravel/valet/issues/1383 for me.

### CODE REVIEW

**Comment by mattstauffer** [comment]
@fylzero Thanks so much for catching this!

**Comment by fylzero** [comment]
> @fylzero Thanks so much for catching this!

@mattstauffer No problem! This might be worthy of a v4.0.1 tag? Currently have to slap 4.x-dev to see the change. Thanks!

**Comment by alesf** [comment]
You can temporarily namespace the LocalValetDriver to Valet\Drivers.

**Comment by mattstauffer** [comment]
@fylzero Sorry, I didn't see this. I normally rely on Dries to tag releases, but I'll push this one out now.

**Comment by mattstauffer** [comment]
Tagged this as v4.0.1: https://github.com/laravel/valet/releases/tag/v4.0.1

**Pull request merged**
