### PR TITLE
Add Magento2 driver

### PR DESCRIPTION
**Pull request by lazyguru**
Here is my version of the Magento2 driver as mentioned at the bottom of #47.  I've been using this as a local driver for several months now and it works great.

I've copied @sschlein instructions for testing from #47 below:

> To test this driver, run the following commands. Please make sure to have an empty database "magento" which can be accessed with the root user without a password on localhost.
> 
> composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento
> 
> cd magento
> 
> chmod a+x bin/magento
> 
> bin/magento setup:install --base-url=http://magento.dev/ \
> --db-host=localhost --db-name=magento --db-user=root --db-password= \
> --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com \
> --admin-user=admin --admin-password=admin123 --language=en_US \
> --currency=USD --timezone=America/Chicago --use-rewrites=1

Also, see http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html for specific PHP extensions that are required to run Magento2

### CODE REVIEW

**Comment by beningreenjam** [comment]
Moving conversation from #47 - I've checked the max_execution_time and its set to 30 seconds but my requests return 404 in 12 seconds or less. I've never used `valet share` before but giving it a try with the grok url it provides sends me into 302 redirect loop on the site home page.

**Comment by lazyguru** [comment]
Did you update core_config_data with the ngrok URL and then clear cache?  Also, you might get stuck in the 302 loop if you are trying to use SSL.  I've found I had to modify the index.php to add:

```
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
      $_SERVER['HTTPS'] = 'on';
      $_SERVER['X-Forwarded-Proto'] = 'https';
      $_SERVER['SERVER_PORT'] = 443;
}
```
to the top of index.php (or you might be able to tell Magento to use the HTTP_X_FORWARDED_PROTO header for SSL offloading)

**Comment by beningreenjam** [comment]
Ah yes the config file, silly forgetful me. No more redirects but back to the original problem of getting 404 on all static files.

The files do exist but not under the versionXXXXXX directory. Guessing the rewrite rule in .htaccess file takes care of that but according to the solution of [this StackExhange question](http://magento.stackexchange.com/questions/100264/magento-2-using-nginx-all-static-assets-are-404) the .htaccess file isn't being read. I'm not clued up enough to be modifying nginx.conf files.

**Comment by lazyguru** [comment]
Sorry, just realized I haven't upgraded my install yet so I don't have the version problem. I'll work on that this week and see if I can work the rewrite into the driver

**Comment by lazyguru** [comment]
I have updated the driver to support the rewrite needed for the versions URLs.

**Comment by lazyguru** [comment]
I also updated my gist if you want to grab it to use while we wait for this PR to be merged: https://gist.github.com/lazyguru/686dd5673097b7db1483dc5c817bd4ee

**Comment by lazyguru** [comment]
@taylorotwell @adamwathan please let me know what/if you have any questions or concerns on this driver.  I am willing to support this driver as any issues come up (I use it myself on a daily basis).

**Comment by beningreenjam** [comment]
Yup, everything works now. I even tried it without tunnelling through ngrok as you previously suggested and it works perfectly fine. You're a superstar and thank you :)

**Comment by sschlein** [comment]
For some reason I always get /server.php/ in my Magento URLs and so I can't access the admin area etc.

Fresh Magento 2 driver, clean install - with and without ngrok.

URLs always look like:
http://hackathon.dev/server.php/CMS-PAGE

Any idea where the server.php comes from?

Static files and normal CMS pages work fine when I remove /server.php/ in my URLs

**Comment by lazyguru** [comment]
What is MAGE_MODE set to? Do you have an index.php in both the root of your project and the pub folder? What version of Magento?

**Comment by sschlein** [comment]
Mage Mode is set to developer (but also tried with production) and I have both index.php files. Simply a clean install at that time. The driver is detected and serves the files, it's just this strange server.php in the URLs so I assume Magento 2 detects the server.php from valet and serves this as some kind of host...?

**Comment by lazyguru** [comment]
I don't have that on my local. Which version of M2?

**Comment by sschlein** [comment]
Newest version which you get with a composer command line install.

Can't test it until tomorrow if it's related to the valet share ngrok
tunnel or also with the local dev URL only.

My use case is building a chatbot extension for M2 and the docker setup is
painful slow
Joe Constant <notifications@github.com> schrieb am So. 12. Feb. 2017 um
18:06:

**Comment by lazyguru** [comment]
2.1.3 and 2.1.4 are broken releases (IMO, e.g. multi-site installs don't work at all). I would recommend installing with 2.1.2 and see if you have issues there.

**Comment by sschlein** [comment]
Will check this tomorrow morning and report this back, thanks!
Joe Constant <notifications@github.com> schrieb am So. 12. Feb. 2017 um
18:27:

**Comment by sschlein** [comment]
It also works on 2.1.4!

Install with `--use-rewrites=1` did the trick!

Took me 5 hours on Saturday and just 15 minutes today...

**Comment by lazyguru** [comment]
So no issues any more?

**Comment by sschlein** [comment]
Nope, works fine and already working on a blog post. M2 is a beast!
Joe Constant <notifications@github.com> schrieb am Mo. 13. Feb. 2017 um
18:20:

**Comment by semmiverian** [comment]
hey @lazyguru  may i ask something out of topics about this driver but still related about magento, so i already installed and link my mcrypt using brew. 

But i always got this error
- Exception: Notice: Use of undefined constant MCRYPT_BLOWFISH
 when try to go to magento.dev

glad if you want to help me.

will delete this if this comment is inappropriate 

i am using php 7.0.14 btw

thanks a lot

**Comment by sschlein** [comment]
Hi @semmiverian 

have you tried this?

http://magento.stackexchange.com/questions/100985/problem-with-magento-2-0-2-ce-after-upgrading-to-php7-0

Keep in mind restarting valet after this change:

`valet restart`

**Comment by semmiverian** [comment]
Hi @sschlein yeah i try this but i've got nothing when try to grep mcrypt 

my brew command to install this is brew instal php70-mcrypt 


and i even got another error when restarting valet like this

-Parse error: syntax error, unexpected '.15' (T_DNUMBER), expecting ',' or ')' in Command line code on line 2/cli/valet.php

**Comment by sschlein** [comment]
Have you tried turning it on and off again? ;)

As you can see in this thread, I was struggling for hours a few weeks ago. At some point, valet stopped working completely and I needed a restart of my Mac to start all services again. I remember similar issues.

**Comment by baublet** [comment]
Ping. It would be great if we could get this merged! The driver itself seems to work fine for me.

**Comment by sschlein** [comment]
I'm using it daily for Magento 2 development so I think this is a huge benefit for the Magento community and could power the development of the 250.000 Magento stores out there.

Magento itself provides only a Docker and a Vagrant setup and both are unusable slow on a Mac.

**Comment by adamwathan** [comment]
Sure what the hell 🤷🏻‍♂️

**Comment by sschlein** [comment]
You are my hero 👍

**Comment by baublet** [comment]
Eyyy, thanks Adam. The Magento community will solute you!

**Pull request merged**
