### PR TITLE
Disable brew auto cleanup on installation

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
When you change the php version and brew stumbles in auto cleanup mode which can fail but is unrelated to the version change in that case. So I just added the environment variable to these calls.

```
==> `brew cleanup` has not been run in 30 days, running now...
Removing: /usr/local/Cellar/krb5/1.18.2... (162 files, 4.0MB)
Removing: /usr/local/Cellar/oniguruma/6.9.5-rev1... (16 files, 1.3MB)
Error: Could not remove php keg! Do so manually:
  sudo rm -rf /usr/local/Cellar/php/7.4.9
Removing: /usr/local/Cellar/php/7.4.9... (497 files, 72.2MB)


In Brew.php line 140:
                                         
  Brew was unable to install [php@7.4].  
                                         

use <phpVersion>
```

### CODE REVIEW

**Comment by mattstauffer** [comment]
Tests fail after this. I'll probably work to update the tests later.

**Comment by JoshuaBehrens** [comment]
I totally forgot about this pull request :O thank you very much for still looking into it :)

**Comment by mattstauffer** [comment]
Thanks for this PR!

**Comment by JoshuaBehrens** [comment]
Thank you for merging it :)

**Pull request merged**
