### PR TITLE
Add 'parked' command to show all sites which have been parked

### PR DESCRIPTION
**Pull request by jrbarnard**
Feature to provide functionality requested in #799 

Added under a separate command to be used alongside 'links' for only parked paths.

I left Site::getLinks as I wasn't sure if I should just replace it's usage with the newly added Site::getSites, I can do if that would be better.

Screen Shot 2019-10-02 at 12 32 04

### CODE REVIEW

**Comment by jrbarnard** [comment]
If merged we'll need to add a PR to the Laravel valet docs

**Comment by drbyte** [comment]
Nicely done.

I'd suggest we mark `getLinks` as deprecated with a docblock, mentioning to use `getSites` instead.  And then update the call to it in the function above your new parked function.

(I'd get rid of it altogether, except that there's a tiny rare chance that someone's written an extension that would be broken. Then again, it's such a minor change that any extension could be easily and quickly fixed without creating crazy hardship. This isn't production.)

**Comment by drbyte** [comment]
👍

**Comment by jrbarnard** [comment]
@drbyte Sounds good, I've marked as @deprecated for now.

**Comment by mattstauffer** [comment]
@jrbarnard This looks great. Would you mind fixing the merge resolution issue?

**Comment by jrbarnard** [comment]
@mattstauffer No problem, I've updated my branch now to remove the conflict

**Comment by mattstauffer** [comment]
Thanks @jrbarnard!

**Comment by mattstauffer** [comment]
OK, released in 2.5.0. @jrbarnard are you up to do that docs PR?

**Comment by jrbarnard** [comment]
Yeah no problem, what branch on the laravel docs should I pr into?

**Comment by mattstauffer** [comment]
Geez, i dunno. 5.8 maybe?

**Comment by drbyte** [comment]
I dunno what Taylor's preference is. Does he prefer 6.0 and then backport manually? Multiple PRs for each? 5.8 and then he'll merge fwd manually? I dunno.

This is where Valet's docs really diverge from Laravel's docs altogether, unfortunately.

**Comment by jrbarnard** [comment]
I'll go for 5.8 and mention it on the PR so can change if needed. Cheers

**Pull request merged**
