### PR TITLE
[Contao] Support the app_dev.php front controller

### PR DESCRIPTION
**Pull request by leofeyer**
This PR adds support for the `app_dev.php` front controller:

* `http://folder.test/contao/login` -> prod mode
* `http://folder.test/app_dev.php/contao/login` -> dev mode with profiler

### CODE REVIEW

**Comment by mattstauffer** [comment]
@leofeyer I'm not a Contao dev; could you get some other Contao/Valet users to weigh in on this so I don't commit it when I shouldn't? Thanks!

**Comment by leofeyer** [comment]
Sure. Maybe @Toflar can confirm the changes or even make some additions so the driver also supports the Contao manager.

**Comment by Toflar** [comment]
I can approve these changes. I'll add support for the mentioned stuff on occasion in a separate PR.

@mattstauffer so you can be sure you can commit: @leofeyer is the Contao project lead and I'm one of the core team developers. And Contao is based on the Symfony full stack framework so it should be fairly similar. Up to you to decide whether that's enough weight though 😄

**Comment by leofeyer** [comment]
The logic in the [SymfonyValetDriver](https://github.com/laravel/valet/blob/master/cli/drivers/SymfonyValetDriver.php) is different though: they always use `app_dev.php` if it is present and otherwise `app.php` (Symfony 3) or `index.php` (Symfony 4).

My changes implement what they initially recommended for Symfony 3 and what we are still using in Contao: https://symfony.com/doc/3.4/setup/web_server_configuration.html#nginx

**Comment by mattstauffer** [comment]
Sounds great; thanks guys! :) I usually just ask for a second person to test it out, less out of a lack of trust of the OP and more just to get multiple folks weighing in and testing out any new code. :) But having the project lead and a core team dev contriubting is definitely great! Thanks! :)

**Pull request merged**
