### PR TITLE
Add Typo3 and Neos drivers

### PR DESCRIPTION
**Pull request by fschwaiger**
Original of https://github.com/laravel/valet/pull/273 and working version of https://github.com/laravel/valet/pull/151.

### CODE REVIEW

**Comment by steffenbrand** [comment]
This really needs to be merged. It works like a charm and shouldn't be waiting until it's conflicting again.

**Comment by dakira** [comment]
Can you please resolve the conflicts so that this can be merged.

**Comment by joshmanders** [comment]
These do not need merged anymore as you can put custom drivers in Valet. https://laravel.com/docs/5.4/valet#custom-valet-drivers

**Comment by dakira** [comment]
@joshmanders How is that a reason? Are all existing drivers being removed now because you can also create your own custom drivers for them? Typo3 is quite a popular CMS/Framework in Europe.

**Comment by joshmanders** [comment]
@dakira of course not. Just means that we don't need to merge every PR for all types of sites, if you use it, just drop the driver into your own project. done.

**Comment by dakira** [comment]
@joshmanders Sure. I'd suggest an "unsupported 3rd party drivers" page in the docs. But this one I'd really rather see merged. ;)

**Comment by steffenbrand** [comment]
My opinion is that valet will lose its purpose and value, if you stop merging new drivers. Being able to run almost every framework **out of the box** is where I see valets biggest benefit.

**Comment by adamwathan** [comment]
I'll merge this once the conflicts get cleaned up, no biggie.

**Comment by xyNNN** [comment]
What is the current state? Can we merge it @adamwathan ? :)

**Comment by adamwathan** [comment]
Merged!

**Comment by xyNNN** [comment]
This was quick, thanks dude 👍

**Pull request merged**
