### PR TITLE
Add WordPlate driver

### PR DESCRIPTION
**Pull request by vinkla**
Added a driver for the amazing WordPlate framework.

> WordPlate is a modern WordPress stack which tries to simplify the fuzziness around WordPress development.

https://wordplate.github.io/

### CODE REVIEW

**Comment by vinkla** [comment]
🤔 it seems the tests fail but it doesn't look related to this pull request?

**Comment by aaemnnosttv** [comment]
@vinkla Try rebasing the PR against master as it no longer includes php 5.5 in the build matrix 👍

**Comment by vinkla** [comment]
@aaemnnosttv thanks!

**Comment by puredazzle** [comment]
Any ETA on this one?

**Comment by mikaelmattsson** [comment]
+1

**Comment by taylorotwell** [comment]
Going to let this be distributed as a third party driver.

**Comment by vinkla** [comment]
Why? We need to find a solution for this. How are we going to qualify projects to add support for third party applications? Valet won't work?!?

**Comment by vinkla** [comment]
We're recommend projects to work with valet but right now it won't work.

**Pull request closed without merging**
