### PR TITLE
Themosis Driver

### PR DESCRIPTION
**Pull request by ramon-villain**
This driver adds support for [Themosis Framework.](http://framework.themosis.com)

### CODE REVIEW

**Comment by taylorotwell** [comment]
The checks are sort of general. Is there a more specific Themosis file or folder you can check for?

**Comment by ramon-villain** [comment]
The root folder are sort of generic: bootstrap, config, htdocs, storage.
But I guess we could change the folder checking to ```/library/Thms/Config```
or file checking to ```/library/Thms/Config/Environment.php```

**Comment by taylorotwell** [comment]
Yes that file check sounds more specific.

**Comment by ramon-villain** [comment]
fix it!

thanks for your support taylor :)

**Comment by gonzunigad** [comment]
This worked perfectly for me ;)

**Comment by gonzunigad** [comment]
It would be great if you accept this pull request 👍

**Comment by joshmanders** [comment]
@gonzunigad you can add `ThemosisValetDriver.php` from this PR in the directory of your project and it should work. https://laravel-news.com/valet-per-site-drivers

**Comment by mattstauffer** [comment]
Hey! We're re-thinking how we handle drivers, and for now we'll be closing all pull requests for adding new drivers.

For anyone who comes across this pull request later and wants this driver in your Valet, you can still [add these drivers locally](https://laravel.com/docs/valet#local-drivers) in the meantime.

Thanks!

**Pull request closed without merging**
