### PR TITLE
Static file serving for subfolders

### PR DESCRIPTION
**Pull request by chejaziuhin**
This allows static file serving of 'index.php' and 'index.html' files from subfolders when you have a root 'public' folder.

### CODE REVIEW

**Comment by eberkund** [comment]
How will this handle different separators, like `example.test/subdir/` vs `example.test/subdir`

**Comment by chejaziuhin** [comment]
@eberkund I made a change to account for those two different use cases - [26d5d71](https://github.com/laravel/valet/pull/542/commits/26d5d715a8fb680ad402bac8cab793cda05b6643). Both urls should work the same now.

**Comment by kclayton925** [comment]
Any update on this? A designer I work with would benefit from this.

**Comment by drbyte** [comment]
This makes sense. 
And it wouldn't conflict with existing drivers that already have a method for detecting static files, so it's not risking breaking those common configs.

**Comment by davidhsianturi** [comment]
This is very useful, especially if you use Laravel API generator https://github.com/mpociot/laravel-apidoc-generator

**Comment by mattstauffer** [comment]
Has anyone been using this regularly without it interrupting the serving of other static sites/etc.?

**Comment by drbyte** [comment]
I haven't had any problems serving Laravel and non-Laravel sites with this change in place.

**Pull request merged**
