### PR TITLE
Remove sudoers entries

### PR DESCRIPTION
**Pull request by leonjza**

### CODE REVIEW

**Comment by taylorotwell** [comment]
If we're going to do this we will probably want to "rm" these files on `valet install` to clean up existing installations.

**Comment by leonjza** [comment]
Maybe just warn instead of deleting in case someone has made modifications?

**Comment by joshmanders** [comment]
I'm still curious as to why this PR is happening, can we get some insights?

**Comment by leonjza** [comment]
@joshmanders as soon as this or a similar fix is available in a tagged version of valet, ready for upgrade, I'll provide the details. @taylorotwell indicated in a email conversation that that may happen next week.

**Comment by adamwathan** [comment]
Agree with Taylor that we should check for those files and delete them on install, not worried about catering to anyone who made modifications :)

@joshmanders the gist of it is that it's probably just not a great idea for us to give Valet the ability to run as `sudo` without a password sort of silently as part of the installation process. If folks want Valet to be able to run without entering a password all the time, it's probably safer for that to be an opt-in thing that they can add themselves. There's risks to anything being able to run as sudo without a password, and right now we've been opting people into that risk without them necessarily being aware.

Theoretically if some other script you downloaded and ran went and modified your copy of the Valet source to do something malicious, Valet would be able run that malicious code with root access without a password prompt. I'm not personally that worried about that actually happening (any random code you download and run from the internet can of course cause problems), but it's probably still better for us to change this by default.

**Comment by joshmanders** [comment]
Ah okay, that makes sense.

**Comment by leonjza** [comment]
@taylorotwell / @adamwathan just double checking here, is the expectation for me to add the deletion of the existing files as mentioned in the PR too? Or will this suffice from my side?

**Comment by adamwathan** [comment]
If you could that would be great! If you don't have time we will just merge as-is and try and make time to add it.

**Comment by leonjza** [comment]
In all fairness I don't think I am going to get a gap to add this, let alone add it in the 'correct' place. I feel this should just be merged for now so that new installs can stop doing this.

Thanks!

**Comment by leonjza** [comment]
Sorry to be a pain about this, but is there any ETA on when the next tagged release will occur that will include this?

**Comment by adamwathan** [comment]
Tagged today 👍

**Comment by leonjza** [comment]
Awesome thank you.

**Pull request merged**
