### PR TITLE
Enable subdomains

### PR DESCRIPTION
**Pull request by tobz-nz**
I know this has been talked about before, but I've already done the work so thought I'd post & get some feedback.

So this is very basic way to enable some sort of subdomain structure.
Should be fully backwards compatible, only change is looping through `$valetConfig['paths']` twice, checking first for `$sitename`, then for `$domain` - instead of checking them both in the same loop.

The payoff being you can now structure your folders like `project1.company`, `project2.company` - matching `project1.company.test`, `project2.company.test` etc..

In my case I also have a company folder: `company/project1.company` etc.. adding more organzation. (just have to `park` the company folder).

### CODE REVIEW

**Comment by drbyte** [comment]
Do I understand correctly?

If I `park` my `~/Sites` folder then this change would allow the following:

Folder | URL
------ | ---
`~/Sites/project1.example` | `http://project1.example.test`
`~/Sites/project2.example` | `http://project2.example.test`

And your footnote about parking a `company` folder would mean if one wants to group projects by company they would `park` the `company` folder (even if it's a subdirectory of an already-parked folder) and then the following would work:

Folder | URL
------ | ---
`~/Sites/example/project1.example` | `http://project1.example.test`
`~/Sites/example/project2.example` | `http://project2.example.test`

but the following, which removes the `.example` suffix from the foldername would not be supported:

Folder | URL
------ | ---
`~/Sites/example/project1` | `http://project1.example.test`
`~/Sites/example/project2` | `http://project2.example.test`

**Comment by tobz-nz** [comment]
@drbyte Yes that's all correct.

**Comment by drbyte** [comment]
I'm okay with this as it stands.

I do wonder if people will want the `domain/subdomain` folder structure without needing to `park` the `domain` and still name the subdirs as `domain/subdomain.domain` for it to work.

I imagine when @mattstauffer reviews the code he'll want you to update the indentation to match the surrounding code.

**Comment by tobz-nz** [comment]
@drbyte Yeah I agree, not having to park the folder would be ideal - this just seemed the easiest, least disruptive way to get it working.

I don't see what's wrong with the indentation..?

**Comment by drbyte** [comment]
Re: indenting. False alarm. My bad. I've been reviewing too many diffs today, and misread this one! :)

**Comment by mattstauffer** [comment]
This is a great PR! It's a useful feature but also an opinionated solution, so I'm going to run this up the chain to Taylor and Adam.

**Comment by tobz-nz** [comment]
Any movement on this PR? Feedback from Taylor/Adam?

**Comment by mattstauffer** [comment]
@tobz-nz Sorry for the delay. Crazy summer. Asking again. :)

**Comment by mattstauffer** [comment]
Closing as this feature was, apparently, already added at some point in the last three years 😆  Thanks for the PR @tobz-nz!

**Comment by joelbutcher** [comment]
@mattstauffer is this feature documented anywhere? Seems like it would be useful to know for some people

**Comment by mattstauffer** [comment]
@joelbutcher 🤷  haha I honestly don't keep up with the Valet documentation.. I know I'll need to but I'd be more than happy for someone else to PR this to the docs if they had time/energy :)

**Pull request closed without merging**
