### PR TITLE
PHPUnit: Convert deprecations to exceptions

### PR DESCRIPTION
**Pull request by bram-pkg**
On PHP 8.1 there are a lot of deprecation warnings.

### CODE REVIEW

**Comment by driesvints** [comment]
I don't see any warnings in the build. Are you on the latest Valet version and its dependencies? Have you run `composer global update`?

**Comment by bram-pkg** [comment]
I have run composer global update, yes. Valet latest version, too.

**Comment by bram-pkg** [comment]
After some further investigation, my `illuminate/container` seems to be stuck on 5.x. I will try and figure out why that is happening.

**Comment by bram-pkg** [comment]
I have made sure that the `illuminate` packages are on the latest version, yet I still get deprecation warnings:

```
>  ~ valet on-latest-version

Deprecated: Return type of Httpful\Response\Headers::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/b.ceulemans/.composer/vendor/nategood/httpful/src/Httpful/Response/Headers.php on line 37

Deprecated: Return type of Httpful\Response\Headers::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/b.ceulemans/.composer/vendor/nategood/httpful/src/Httpful/Response/Headers.php on line 46

Deprecated: Return type of Httpful\Response\Headers::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/b.ceulemans/.composer/vendor/nategood/httpful/src/Httpful/Response/Headers.php on line 58

Deprecated: Return type of Httpful\Response\Headers::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/b.ceulemans/.composer/vendor/nategood/httpful/src/Httpful/Response/Headers.php on line 67

Deprecated: Return type of Httpful\Response\Headers::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/b.ceulemans/.composer/vendor/nategood/httpful/src/Httpful/Response/Headers.php on line 75
Yes
```

**Comment by driesvints** [comment]
Seems like those are due to Httpful which doesn't seems to be actively maintained anymore. I think it might be better if we switch to a more mature library like Guzzle.

**Comment by driesvints** [comment]
I'm gonna close this one as there's nothing we can do atm without switching to a different HTTP library.

**Comment by bram-pkg** [comment]
I have opened a PR that replaces HTTPful with Guzzle.

**Comment by driesvints** [comment]
@bram-pkg how did you make sure the illuminate components were on the latest version? I'm starting to get the `Method ReflectionParameter::getClass() is deprecated` now as well.

**Comment by bram-pkg** [comment]
I global required illuminate ^8.0

**Comment by rikiless** [comment]
"illuminate/container": "^8.0" in global composer.json helped.

**Pull request closed without merging**
