### PR TITLE
Dry's up PHP installation

### PR DESCRIPTION
**Pull request by KennedyTedesco**

### CODE REVIEW

**Comment by drbyte** [comment]
I agree: using `$this->brew->hasInstalledPhp()` as you've done is better than re-listing every PHP version in another file.

**Comment by KennedyTedesco** [comment]
@drbyte Thanks for reminding me. Looks like we have some conflicts here, I'll fix them soon as possible. 😄

**Comment by adamwathan** [comment]
Can you resolve the merge conflicts? Happy to merge after that.

**Comment by KennedyTedesco** [comment]
Sorry, I'll close and open another one. I've lost the branch.

**Pull request closed without merging**
