### PR TITLE
(WIP) Extract for multi-OS support

### PR DESCRIPTION
**Pull request by mattstauffer**
Commands I've tested and made work:
- [ ] composer
- [ ] diagnose
- [x] directory-listing
- [ ] fetch-share-url
- [ ] forget
- [ ] install
- [ ] isolate
- [ ] isolated
- [x] link
- [x] links
- [ ] log
- [ ] loopback
- [x] on-latest-version
- [ ] open
- [x] park
- [ ] parked
- [x] paths
- [ ] php
- [ ] proxies
- [ ] proxy
- [ ] restart
- [ ] secure
- [ ] secured
- [ ] set-ngrok-token
- [ ] share
- [ ] share-tool
- [ ] start
- [ ] status
- [ ] stop
- [ ] tld
- [ ] trust
- [ ] uninstall
- [ ] unisolate
- [ ] unlink
- [ ] unproxy
- [ ] unsecure
- [ ] use
- [x] which
- [x] which-php

### CODE REVIEW

**Comment by mattstauffer** [comment]
Next up: `valet install`, since it hits just about everything.

Right now, this is what you get:
image

So I need t work through the todo on phpfpm, make sure the Dnsmasq is actually working correctly, and then dig into the Nginx errors.

**Comment by mattstauffer** [comment]
Latest version runs into this error; I don't love this whole "use with caution in scripts". But.. looks like my next steps are to force it to confirm, and to hide the output when it's running.

image

**Comment by mattstauffer** [comment]
I'm not saying it's all actually working but we've made some steps here...

image

No errors on install!!

**Comment by mattstauffer** [comment]
Closing this. I made good progress, but it's clear that Dnsmasq *alone* is so different between macOS and Linux *and* so different between different Linux setups and distros that this is just not tenable as a light layer on top of Valet like I imagined.

**Comment by yCodeTech** [comment]
I've been working on my own fork of the very much outdated and unmaintained Valet Windows by cretueusebiu. I am on the home straight and hope to release it as [Laravel Valet Windows 3](https://github.com/yCodeTech/valet-windows) in the very near future. I hope to gain as much parity as possible from this macOS, and I've been going through the open PRs to make sure it's on par and squash any bugs.

**Pull request closed without merging**
