### PR TITLE
Fix large-upload problems by setting PHP limits and Nginx max size

### PR DESCRIPTION
**Pull request by drbyte**
- Sets `client_max_body_size 128M` in `http` section of `nginx.conf`  so it covers all configs
- Adds `php-memory-limits.conf` to `php-fpm` conf folder, to set `memory_limit`, `upload_max_filesize`, `post_max_size` all to 128M

(Updates #253 by moving config location to cover all, since #253 didn't cover secure configs, etc)

### CODE REVIEW

**Comment by bbashy** [comment]
`post_max_size` should be larger than `upload_max_filesize`.

If you upload a 128MB file and some POST data, it will be too large.

**Comment by drbyte** [comment]
At 128 MB it didn't seem like there'd be much risk of hitting that threshold in 2017. It's easily configurable for those who know they're going to hit such a rare size on a regular basis.

But ... instead of just saying "it should be larger", can you recommend a specific value that you believe to be exactly the right choice?

**Comment by bbashy** [comment]
Yeah of course, I was just going by the docs on PHP (and what I've always done) for setting post data size larger than upload size. Memory limit should also be larger than post data size.

I think memory limit at 128M is fine. Maybe set the rest like this.

```
;Max memory per instance
memory_limit = 128M

;The maximum size of an uploaded file.
upload_max_filesize = 100M

;Sets max size of post data allowed. This setting also affects file upload. To upload large files, this value must be larger than upload_max_filesize
post_max_size = 125M
```

**Comment by adamwathan** [comment]
Going to merge as is for now, if anyone has better ideas for the sizes happy to discuss in a new PR.

**Pull request merged**
