### PR TITLE
Add Generic Driver to point to a public/ folder

### PR DESCRIPTION
**Pull request by svpernova09**
Adds Generic Support to a `public/` folder containing an `index.php` file.  Adds support for SlimPHP, Non-Framework PHP apps.

### CODE REVIEW

**Comment by igorpan** [comment]
Wouldn't this block any other more strict Driver from working? Laravel one for example?

**Comment by svpernova09** [comment]
Possibly, it may be the default driver will work as a generic

**Comment by CHH** [comment]
I think something like this should be included in Valet. When I installed Valet, I expected plain php files to just work out of the box, but was surprised that it didn't work.

**Comment by CHH** [comment]
We could also think about something like a `Valetfile`, which can configure most common options, like public directory, front controller and an override for the driver.

**Comment by svpernova09** [comment]
@igorpan Turns out as long as it's in the right order it won't conflict.

**Pull request merged**
