### PR TITLE
Recursively search for custom valet drivers

### PR DESCRIPTION
**Pull request by morrislaptop**
This PR searches directories inside `~.valet/Drivers` so that users can easily bring in custom drivers from other packages. 

Before:

    Clone the directory and then copy CustomValetDriver.php into your ~/.valet/Drivers directory

After:

    git clone https://github.com/DCzajkowski/DistValetDriver.git ~/.valet/Drivers/DistValetDriver`

### CODE REVIEW

**Comment by morrislaptop** [comment]
No?

**Comment by drbyte** [comment]
Tests good. 
Great idea -- adds simplicity!

**Comment by mattstauffer** [comment]
Whoops, not sure how I missed this one entirely. Thanks @morrislaptop, @drbyte, and @morrislaptop's glorious mustache.

**Comment by drbyte** [comment]
TECH NOTE: Since Valet 2.1.0 in Sept 2018, the config dir is now `~/.config/valet` and not `~/.valet` as mentioned in the comments above.
Other than that, the concept still works as intended.

**Pull request merged**
