### PR TITLE
Show start & stop process info in terminal

### PR DESCRIPTION
**Pull request by antonioribeiro**
Give users some info while starting, stopping and restarting services:

image

### CODE REVIEW

**Comment by adamwathan** [comment]
Any particular reason for adding this, or just prefer seeing the output?

**Comment by antonioribeiro** [comment]
It's important to know what's happening under the hoods. Did it really restarted NGINX, and PHP? When things aren't working (for some other reason) I just restart them manually to be sure...

**Comment by adamwathan** [comment]
The problem is even when Homebrew tells me it really started nginx I still don't believe it and have to run `ps aux | grep nginx` half the time, hahaha... But yeah I hear you 👍 If you can fix those conflicts whenever you have time I'll merge.

**Comment by antonioribeiro** [comment]
@adamwathan , can we extend it to install? 

image

**Comment by adamwathan** [comment]
Yeah sure add the logs for install too 👍

**Comment by antonioribeiro** [comment]
Done.

**Comment by bbashy** [comment]
There's about 2 other PRs that are editing the same file so as long as this gets merged soon, should be OK!

**Comment by adamwathan** [comment]
Thanks again!

**Pull request merged**
