### PR TITLE
LaravelValetDriver update, so that supports both public and public_html

### PR DESCRIPTION
**Pull request by jpcursor**
Handy in pre-configured servers e.g. cPanel

Add in bootstrap/app.php before the App return:

$app->bind('public.path', function (){
    return base_path('/public_html');
});

And then you're ready to change your public folder to public_html

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
How is this pull request different than #187? Looking at the changes side by side they are the same. Can you close one of em?

**Comment by jpcursor** [comment]
Hello Korvin,

Sorry, i'm a one man army, so i'm not very experienced with open source...
(branches etc)

So I made PR in the master and sierra braches..

Should have done differentely??

Soon i'm schedueling more time to open source, packages etc, will perform
better :

Sure, tell me which should i close?

**Comment by KorvinSzanto** [comment]
Oh I see, disregard what I said :)

**Comment by taylorotwell** [comment]
Would prefer this just be a separate driver. Laravel typically is designed to work with a public directory.

**Pull request closed without merging**
