### PR TITLE
Forbid access to most commands if not installed

### PR DESCRIPTION
**Pull request by antonioribeiro**
If valet is not yet installed we get all sort of errors on commands, like

image

So I thought we could just show this, while not installed:

image

### CODE REVIEW

**Comment by drbyte** [comment]
I like the idea.
I do wonder if coding-wise we could just do an early exit if not fully installed, instead of nesting all the code in a big `if` block. 

ie: pseudocode, for right after the `install` block, something like:
`if (!is_dir(VALET HOME)) {
  app->run;
  exit();
}
`

**Comment by antonioribeiro** [comment]
@drbyte, I agree with you about the fact the code is kind of unbeautiful the way I did it. But an early exit may make it even more odd. The problem, I think, is that valet.php could use some refactoring, at least to  move command instantiation to a service class or something, and make the whole thing less linear/procedural. While thinking the best approach I almost used an **ELSE** and a **GOTO**. :)

Anyway, Laravel is a highly opinionated community, so PRs here are much more a way to show an idea, than code written in stone. So the core team is obviously free to take the path they prefer.

Just tell me what's the decision and I'll make the necessary changes to the code.

**Comment by adamwathan** [comment]
Yeah happy to merge as-is with the big if statement honestly, fine with me. Can you resolve the current merge conflicts then I can merge?

**Comment by antonioribeiro** [comment]
Sure, will do it later in the afternoon, here.

**Comment by antonioribeiro** [comment]
Conflicts resolved.

**Comment by bbashy** [comment]
This needs to be done sooner else you'll keep getting conflicts as it's a whole file update :)

**Comment by antonioribeiro** [comment]
Conflicts resolved once again.

**Comment by bbashy** [comment]
There's about 2 other PRs that are editing the same file so hopefully it gets merged soon.

**Pull request merged**
