### PR TITLE
Rename `valet domain` command to `valet tld`

### LINKED ISSUE #144: "Domain" should maybe be "TLD"?
Every time I read the command `domain` I think it has to do with the domain (e.g. `burgermergency`) of the folder I'm in. When I think of the "ending" (.com, .net, etc.) I think of that as the `TLD`.

I want to ask before I PR, because I don't know if everyone else thinks of this different from me. But I'd propose changing `domain` to `tld` so it's clearer that it's not talking about the domain of the current folder you're in, but instead your global `tld` for Valet.

Thoughts?

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #144 proposed by @mattstauffer 

`.dev` is really a TLD, not a "domain" in the conventional sense.

Changing the command to `valet tld` more accurately reflects the purpose of the command (which is to set or get the configured TLD served by Valet)

### CODE REVIEW

**Comment by adamwathan** [comment]
Hey @drbyte if you have time to fix whatever is conflicting here, I'm happy to merge after that. Thanks!

**Comment by drbyte** [comment]
@adamwathan done.

**Comment by drbyte** [comment]
Conflicts resolved

**Comment by drbyte** [comment]
@adamwathan This has been updated to fix latest merge conflicts after today's merges.

As discussed, `valet domain` is now an alias for `valet tld`, until such time as you want to remove the alias.
And the `config.json` now contains the `tld` key for configuration purposes (copied from the `domain` key, but preserves the `domain` key's old value for regression safety; again, can be more safely cleaned away in a future version)

**Comment by drbyte** [comment]
Merge conflicts fixed. Tests passing again.

**Comment by mattstauffer** [comment]
Thanks @drbyte!

**Pull request merged**
