### PR TITLE
Add support to Symfony Flex directory structure

### PR DESCRIPTION
**Pull request by IndraGunawan**
reference: https://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex

### CODE REVIEW

**Comment by jerguslejko** [comment]
Wouldn't this remove support for previous versions of Symfony?

**Comment by IndraGunawan** [comment]
@jerguslejko current driver using old directory structure of Flex, so i just change to new directory structure of Flex.
ref: http://fabien.potencier.org/symfony4-directory-structure-updates.html

**Comment by simensen** [comment]
On checking this again, I think I see what @IndraGunawan did here. The driver had previously supported the old Flex structure. I hadn't realized that. :)

So the only thing that was changed is that the `index.php` for Flex applications (which weren't there at all for older Symfony applications) is in `public` instead of `web`.

**Comment by simensen** [comment]
👍 LGTM

**Comment by simensen** [comment]
@adamwathan I believe this one should be ready to go as well.

**Comment by taylorotwell** [comment]
Thanks

**Pull request merged**
