### PR TITLE
Update valet

### PR DESCRIPTION
**Pull request by golubkovden**
Suppress error message if file not exists

### CODE REVIEW

**Comment by drbyte** [comment]
Hi,
Can you explain how you triggered a problem which required this?

I just did the following, and don't get any errors about files missing:

```sh
cd ~/Sites   #this is my parked valet dir
laravel new sharetest
cd sharetest
ls -al ~/.config/valet/Nginx/share*   #no results found
valet share
```
Ngrok opened properly, and visiting the presented URL shares the new Laravel site correctly.
In fact, all the ngrok links, both http and https for ngrok and for sharetest.test show the new Laravel site correctly.

What steps will recreate the symptom you're trying to fix here?

**Comment by golubkovden** [comment]
Hello @drbyte 
Steps to reproduce:

```
composer create-project laravel/laravel sharetest
cd sharetest
valet link 
valet share
```

PS Make sure you don't used `valet secure` and `sharetest` project not inside your park zone

**Comment by drbyte** [comment]
Okay, after hacking around a bit, I was able to see the message.
It seems ngrok was masking the error when it ran (since it clears the screen, etc).

Ya, this can be merged.
Thanks for submitting this @golubkovden

**Comment by mattstauffer** [comment]
Thanks @golubkovden and @drbyte!

**Pull request merged**
