### PR TITLE
Switch to Illuminate Collections

### PR DESCRIPTION
**Pull request by driesvints**
This PR switches Valet to use the new Illuminate Collections instead. This will require a new major release. You might want to split off the current master branch into a `2.x` branch before merging this.

Because we're switching to a new Illuminate component introduced in Laravel 8, we'll have to drop old PHP and Laravel versions.

Valet 2.x can still be maintained simultaneously if needed for people on lower Laravel/PHP versions.

Closes https://github.com/laravel/valet/issues/1011

### CODE REVIEW

**Comment by driesvints** [comment]
One thing that @mattstauffer noted to me is that this'll leave people working on apps on older and newer PHP versions simultaneously in the dark since they won't be able to switch to all versions easily anymore. Ideally we should find a way to offer that somehow.

Unfortunately I don't see how we can do that since requiring both tighten/collect and illuminate/collections can't be done due to namespace conflicts. We could maybe delay all of this until Laravel 10 has been released since tighten/collect will still be maintained for Laravel 8 & 9. When Laravel 10 is released we'll need to update the illuminate/container dependency on Valet and then it might be a good time to phase out all PHP versions below PHP 7.3.

**Comment by driesvints** [comment]
@mattstauffer I don't think we use any tighten/collect namespaces in Valet? They're already Illuminate namespaces (or mostly the `collect` helper? Or am I misunderstanding you?

**Comment by mattstauffer** [comment]
Oh. That could be the case 🤦 didn't even check.

**Comment by driesvints** [comment]
Gonna close this one for now.

**Pull request closed without merging**
