### PR TITLE
[FEATURE] Pretty print sites

### PR DESCRIPTION
**Pull request by joshmanders**
This is an expansion on https://github.com/laravel/valet/pull/234 like discussed in it.

It now shows all links in a table, their link name, if that link is secured, it's url to easily open, and the path of the link.

Preview of output:

### CODE REVIEW

**Comment by morloderex** [comment]
Not sure that protocol is really necessary if we have a column called ssl. :) 
Too me it seems implied.

**Comment by joshmanders** [comment]
The protocol is there because it makes the link clickable on many terminals like iTerm2, and Hyper.

**Comment by joshmanders** [comment]
@adamwathan You think we should also include sites in parked folders? Right now it doesn't do that.

**Comment by joshmanders** [comment]
ping @adamwathan

**Comment by adamwathan** [comment]
Merged as is for now but we can think about parked folders. The output could get pretty out of a control there, so hard to say :/

**Comment by joshmanders** [comment]
Sounds good to me.

**Pull request merged**
