### PR TITLE
Set files path as a static path for concrete5 driver

### PR DESCRIPTION
**Pull request by KorvinSzanto**
Previously, testing a concrete5 site that had tons of 404s and required file based sessions would force each request to load sequentially causing the site to load pretty slowly. This change makes it so that the driver is aware of the files directory and markes anything within as a static file.

### CODE REVIEW

**Comment by mattstauffer** [comment]
@KorvinSzanto Could you ask a few other concrete5 folks to check this out for you, and give us emoji responses so we can verify it's working for multiple folks? None of us use concrete5 so we can't check this.

**Comment by JohntheFish** [comment]
What is the specification on $uri ? Is it site relative, or host relative? If host relative, testing ===0 could have issues with installations in sub-folders.

**Comment by biplobice** [comment]
This helps me a lot for sites which have lots of 404s.
It works fine for me, and the installation in sub-folders didn't work, without this code as well.

**Comment by mattstauffer** [comment]
If we can get more concrete5 folks to check it, we could merge this, but it's been four years since I asked for more input so I'm gonna close it.

**Comment by mattstauffer** [comment]
@KorvinSzanto To be honest, I was looking for comments and didn't even check the emoji responses :)  Please feel free to re-make the PR if you'd like.

**Comment by KorvinSzanto** [comment]
I've restored the branch so this PR should be reopenable. If not I can go ahead and make a new PR

**Comment by mattstauffer** [comment]
@KorvinSzanto Thanks! i just did a merge resolution; can you verify it still works correctly after that?

**Pull request merged**
